export const GameActionTypes = {
  SHOT_COUNTER_INCREMENT: 'SHOT_COUNTER_INCREMENT',
  SERVE_GAME: 'SERVE_GAME',
  SHOT_BALL: 'SHOT_BALL',
  ROBOT_SHOT_BALL: 'ROBOT_SHOT_BALL',
  MOVE_CLOCK: 'MOVE_CLOCK',
  START_GAME: 'START_GAME',
  RESTART_GAME: 'RESTART_GAME',
  END_GAME: 'END_GAME',
  START_RECORD: 'START_RECORD',
  STOP_RECORD: 'STOP_RECORD'
};
