export const MotionActionTypes = {
  MOTION_UPDATE_DATA_SENSORS: 'MOTION_UPDATE_DATA_SENSORS',
  MOTION_FIND_KNOW_SHOT: 'MOTION_FIND_KNOW_SHOT',
  SET_DEVICE_OS: 'SET_DEVICE_OS',
  TOGGLE_RECORD: 'TOGGLE_RECORD'
};